# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('url', models.SlugField(unique=True, verbose_name='URL')),
                ('ceo_keywords', models.TextField(blank=True, null=True, verbose_name='META keywords')),
                ('ceo_description', models.TextField(blank=True, null=True, verbose_name='META description')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ('created',),
            },
        ),
    ]
