# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='has_unread',
            field=models.BooleanField(default=False),
        ),
    ]
