# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationprofile',
            name='password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
