# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='org_form',
            field=models.IntegerField(choices=[(0, 'Private person'), (1, 'Legal entity')], default=0, verbose_name='Form of incorporation'),
        ),
    ]
