# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20160824_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('network_id', models.SlugField(max_length=100, unique=True, verbose_name='Network ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='auto_post_to_networks',
            field=models.ManyToManyField(to='accounts.SocialNetwork', verbose_name='Allow auto post to'),
        ),
    ]
