# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20160901_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='network_id',
            field=models.CharField(blank=True, choices=[('vk-oauth2', 'VK'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('twitter', 'Twitter'), ('odnoklassniki', 'Odnoklassniki')], max_length=20, null=True, unique=True, verbose_name='Network ID'),
        ),
    ]
