# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160517_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Profile link'),
        ),
    ]
