# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160517_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.IntegerField(choices=[(0, 'LIME'), (1, 'ORANGE'), (2, 'NOT DEFINED')], default=2, verbose_name='Theme'),
        ),
    ]
