# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
        ('main', '0004_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackDeliveryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('old_price', models.FloatField(default=0.0, verbose_name='Old price')),
                ('new_price', models.FloatField(default=0.0, verbose_name='New price')),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Used')], default=0, verbose_name='State')),
                ('delivery_time', models.IntegerField(default=1, verbose_name='Delivery time')),
                ('cooperation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cooperation')),
                ('deal', models.IntegerField(choices=[(0, 'Buy-Sell'), (1, 'Sale'), (2, 'Auction')], default=0, verbose_name='Type of deal')),
                ('valid_through', models.DateField(blank=True, null=True, verbose_name='Valid through')),
                ('purchase_returns_time', models.IntegerField(default=1, verbose_name='Purchase returns time')),
                ('delivery_description', models.TextField(blank=True, null=True, verbose_name='Delivery description')),
                ('back_delivery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BackDeliveryForm', verbose_name='Back delivery form')),
                ('delivery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DeliveryForm')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GoodsPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='goods', verbose_name='Image')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_photos', to='main.Good')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='GoodsProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('trade_mark', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade mark')),
                ('material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Material')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('equipment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipment')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Weight')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor')),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='main.Good')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(max_length=12, verbose_name='Language code')),
                ('translated_text', models.TextField(verbose_name='Translated text')),
                ('good_properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GoodsProperties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='good',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Refund', verbose_name='Refund'),
        ),
        migrations.AddField(
            model_name='good',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to=settings.AUTH_USER_MODEL),
        ),
    ]
