# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160518_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Offline'), (1, 'Online')], default=1, verbose_name='User online status'),
        ),
    ]
