# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='delivery_form',
            field=models.IntegerField(choices=[(0, 'Logistic'), (1, 'Mail'), (2, 'Courier'), (3, 'Hands'), (4, 'Pickup')], default=1, verbose_name='Delivery form'),
        ),
        migrations.DeleteModel(
            name='DeliveryForm',
        ),
    ]
