# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160520_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsproperties',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight'),
        ),
    ]
