# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160520_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='good',
            name='cooperation',
            field=models.CharField(default='All countries', max_length=255, verbose_name='Cooperation'),
        ),
    ]
