# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160520_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='valid_through',
        ),
        migrations.AlterField(
            model_name='good',
            name='delivery_time',
            field=models.CharField(blank=True, default='1', max_length=128, null=True, verbose_name='Delivery time'),
        ),
        migrations.AlterField(
            model_name='goodsproperties',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (kg.)'),
        ),
    ]
