# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_activationprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='good',
            name='back_delivery_form',
        ),
        migrations.RemoveField(
            model_name='good',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='good',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='good',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goodsphotos',
            name='good',
        ),
        migrations.RemoveField(
            model_name='goodsproperties',
            name='good',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='social_network',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='translatedtext',
            name='good_properties',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivationProfile',
        ),
        migrations.DeleteModel(
            name='BackDeliveryForm',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='GoodsPhotos',
        ),
        migrations.DeleteModel(
            name='GoodsProperties',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
        migrations.DeleteModel(
            name='TranslatedText',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
