# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='max_price',
            field=models.FloatField(default=0.0, verbose_name='Max price (Auction)'),
        ),
        migrations.AddField(
            model_name='good',
            name='min_price',
            field=models.FloatField(default=0.0, verbose_name='Min price (Auction)'),
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price (Buy-Sell)'),
        ),
        migrations.AddField(
            model_name='good',
            name='reserve_price',
            field=models.FloatField(default=0.0, verbose_name='Reserve price (Auction)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='new_price',
            field=models.FloatField(default=0.0, verbose_name='New price (Sale)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='old_price',
            field=models.FloatField(default=0.0, verbose_name='Old price (Sale)'),
        ),
    ]
