# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0003_goodscomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='goods_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
