# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='back_delivery_form',
            field=models.IntegerField(choices=[(0, 'Due to buyer'), (1, 'By seller')], default=0, verbose_name='Back delivery form'),
        ),
        migrations.AlterField(
            model_name='good',
            name='purchase_returns_time',
            field=models.CharField(default='1', max_length=128, verbose_name='Purchase returns time'),
        ),
        migrations.AlterField(
            model_name='good',
            name='refund',
            field=models.IntegerField(choices=[(0, 'Monetary equivalent'), (1, 'Replacement product')], default=0, verbose_name='Refund'),
        ),
        migrations.DeleteModel(
            name='BackDeliveryForm',
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
