# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20160610_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionbids',
            name='user_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='User price'),
        ),
        migrations.AlterField(
            model_name='good',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Max price (Auction)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Min price (Auction)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='New price (Sale)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Old price (Sale)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price (Buy-Sell)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='reserve_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Reserve price (Auction)'),
        ),
        migrations.AlterField(
            model_name='goodsproperties',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight (kg.)'),
        ),
    ]
