# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20160615_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='good',
            name='valid_through',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valid through'),
        ),
    ]
