# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='ready_for_sale',
            field=models.BooleanField(default=True, verbose_name='Ready for sale (auction)'),
        ),
    ]
