# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-14 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartmodel_ready_for_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartModel',
            new_name='AuctionCartModel',
        ),
    ]
