"""
Django settings for storesb project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$fblbjvdi6ha5+_qr(gkeg&3!*6m6x7m_%4zr$2@%us@*yt_a@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'filebrowser',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taggit',
    'sorl.thumbnail',
    'django.contrib.sites',
    # For develop purposes - in production use Redis or RabbitMQ
    'kombu.transport.django',
    'djcelery',
    'social.apps.django_app.default',
    'django_extensions',
    'tinymce',
    'django_social_share',
    # APPS
    'main',
    'goods',
    'accounts',
    'complaints',
    'orders',
    'chat',
    'cart',
    'pages',
    'parler',
    'django.contrib.admin',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'storesb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'goods.context_processors.const_processor',
                'cart.context_processors.cart',
                'accounts.context_processors.accounts_processor',
                'main.context_processors.get_site'
            ],
        },
    },
]

WSGI_APPLICATION = 'storesb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'storesbdb',
        'USER': 'storesbuser',
        'PASSWORD': 'XSW@!qaz',
        'HOST': 'localhost',
        'PORT': '',                      # Set to empty string for default.
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('ru', 'Russian'),
    ('en', 'English'),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),

)

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = '/home/ubuntu/workspace/storesb/static'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# MEDIA SETTINGS
MEDIA_ROOT = (os.path.join(BASE_DIR, 'media'))

MEDIA_URL = '/media/'

# SITE ID
SITE_ID = 1

# SMS AERO SETTINGS
SMSAERO_URL = 'https://gate.smsaero.ru/send/'
SMSAERO_LOGIN = 'NataliaArton@gmail.com'
SMSAERO_PASSWORD = 'Fuckoff27'
SMSAERO_RESPONSE_FORMAT = 'json'
SMSAERO_GROUP = 'NEWS'

# LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'standard': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
    },
    'handlers': {
        # 'null': {
        #     'level':'DEBUG',
        #     'class':'django.utils.log.NullHandler',
        # },
        'logfile': {
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR + "/logfile",
            'maxBytes': 50000,
            'backupCount': 2,
            'formatter': 'standard',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter': 'standard'
        },
    },
    'loggers': {
        'django': {
            'handlers':['console'],
            'propagate': True,
            'level':'WARN',
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'main': {
            'handlers': ['console', 'logfile'],
            'level': 'DEBUG',
        },
        'accounts': {
            'handlers': ['console', 'logfile'],
            'level': 'DEBUG',
        },
        'goods': {
            'handlers': ['console', 'logfile'],
            'level': 'DEBUG',
        },
    }
}

# EMAIL BACKEND (for developing process)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'storesb.robot@gmail.com'
EMAIL_HOST_PASSWORD = '1qazXSW@1qazXSW@'
FAIL_EMAIL_SILENTLY = False

# Celery settings
# BROKER_URL = 'django://'
BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'

# LOGIN URLS
LOGIN_REDIRECT_URL = reverse_lazy('accounts:profile')
LOGIN_URL = reverse_lazy('accounts:login')

# AUTHENTICATION
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'accounts.authentication.TokenAuthBackend',
    'accounts.authentication.EmailAuthBackend',
    'social.backends.facebook.Facebook2OAuth2',
    'social.backends.pinterest.PinterestOAuth2',
    'social.backends.vk.VKOAuth2'
)

# GOOGLE API KEYS
GOOGLE_GEOCODING_KEY = 'AIzaSyDp0ANx34jzCP9DVsGtejZZJeSoHgSx-K4'

# SESSION STORE
SESSION_ENGINE = 'redis_sessions.session'

# CHAT SETTINGS
MESSAGE_API_KEY = 'gEWBGnBqp91oatQw12Q2soUxogSN6q+SRzARgB0q1Wc='
MESSAGE_API_URL = 'http://192.168.100.100/chat/send_message_api/'

#REDIS SETTINGS
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

# CART SESSION VARIABLE
CART_SESSION_ID = 'cart'


# PYTHON-SOCIAL-AUTH SETTINGS
SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
)

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
  # 'locale': 'ru_RU',
  'fields': 'id, name, email, age_range'
}

SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['wall', 'email']

# NO GOOD IMAGE
NO_GOOD = 'images/no-good-image.png'

# TINYMCE SETTINGS

# TINYMCE SETTINGS
TINYMCE_FILEBROWSER = True
TINYMCE_DEFAULT_CONFIG = {
    'plugins': "table,paste,searchreplace",
    'theme': "advanced",
    'mode': "textareas",
    'file_browser_callback': 'mce_filebrowser',
    'theme_advanced_buttons3_add': "tablecontrols",
    'table_styles': "Header 1=header1;Header 2=header2;Header 3=header3",
    'table_cell_styles': "Header 1=header1;Header 2=header2;Header 3=header3;Table Cell=tableCel1",
    'table_row_styles': "Header 1=header1;Header 2=header2;Header 3=header3;Table Row=tableRow1",
    'table_cell_limit': 100,
    'table_row_limit': 5,
    'table_col_limit': 5,
    'style_formats': [
        {'title': 'Bold text', 'inline': 'strong'},
        {'title': 'Red text', 'inline': 'span', 'styles' : {'color' : '#ff0000'}},
        {'title': 'Help', 'inline': 'strong', 'classes' : 'help'},
        {'title': 'Table styles'},
        {'title': 'Table row 1', 'selector': 'tr', 'classes': 'tablerow'}
    ],
    'width': '1140',
    'height': '800',
}

# django-parler settings
PARLER_LANGUAGES = {
    SITE_ID: (
        {'code': 'en',},
        {'code': 'ru',},
    ),
    'default': {
        'fallback': 'en',
        'hide_untranslated': False,
    }
}